### ISSUE TITLE
Fork Bitcoin Core explicitly

### ISSUE THREAD

**Issue by dexX7** [bitcoinxt/bitcoinxt#12]
Bitcoin XT, while being a fork of Bitcoin Core, isn't considered as one by GitHub. Unfortunally this prevents comparing the changes made to Bitcoin XT, for example via GitHub's [fork compare](https://help.github.com/articles/comparing-commits-across-time/)/pull request mechanism, which is handy to answer the question: "what exactly is the diff between XT and Core?"

If this wasn't intentional, then I suggest to fork the upstream project explicitly.

**Comment by mikehearn** [comment]
I don't know how to tell github where the repository came from originally. It's not a fork on github because I just uploaded a local repository with changes I already had, rather than creating a fork and then cloning it down and re-applying the changes.

You can easily use "diff -ur" to see the differences, or use the git command line (eg "git diff 0.10.2A..upstream/master"), or just look at the commits as they are all rebased onto the top of the upstream branch.

**Comment by hectorj** [comment]
I believe one way would be to delete this repo of Github, re-create it by forking https://github.com/bitcoin/bitcoin and re-push your branches into it.

**Comment by luke-jr** [comment]
Note that fixing this will break GitHub's issue tracker.

**Comment by mikehearn** [comment]
Huh, why?

**Comment by hectorj** [comment]
@mikehearn : I think @luke-jr is talking about the "solution" I described.

"delete this repo of Github" => lose all current issues and pull-requests

**Comment by mikehearn** [comment]
Yeah. I'm not going to do that. I might ask github support to manually edit their db or something, but I don't see why it's a big deal. Just use the command line, no big deal.

**Comment by dexX7** [comment]
@mikehearn: you may indeed contact the GitHub support and ask to update the network/fork status. I was once told by the support, in a similar context, that it's possible to change the parent of a project, if the projects are within the same network, so it looks like it's really just an update in their DB.

> Just use the command line, no big deal.

*Complexity kills kittens* (or whatever)
