### ISSUE TITLE
Implement SIGHASH_WITHINPUTVALUE

### ISSUE THREAD

**Issue by prusnak** [bitcoinxt/bitcoinxt#13]
This would make life SO MUCH easier for all hardware wallets and software wallets that don't have access to the blockchain.

Bitcointalk discussion: https://bitcointalk.org/index.php?topic=181734.0
Bitcoin-devel discussion: http://sourceforge.net/p/bitcoin/mailman/message/33261411/

**Comment by mikehearn** [comment]
It might be easier to just make a new transaction version and alter the behaviour of CHECKSIG when txv=2, no? Does a patch for either approach exist?

I actually discussed this with Gavin earlier today. The sticking point is whether trying to overload the block size fork with other things, even basic and straightforward things like this, would reduce the chances of adoption by confusing people. I'd like to have a better sighash function (+dos fixes) too, but not at the cost of failing to raise the block size limit.

So currently I am feeling undecided about this. Feedback from others would be welcome.

**Comment by prusnak** [comment]
Bumping the issue now that the block size limit is raised. Has anything changed from yours or Gavin's side?

**Comment by gavinandresen** [comment]
I'm gonna close this, "I'd like you to implement..." issues are not useful-- discussions of priorities belong on mailing lists. Mike, if you'd like to have the issue list contain a list of priorities of big tasks to work on, feel free to re-open...

**Comment by mikehearn** [comment]
@prusnak The block size limit has not been raised .... anyone who shows support for BIP 101 gets DoSd off the internet, as you are well aware.

There's no point in discussing further upgrades to the Bitcoin protocol at the moment. It may as well be frozen as far as I'm concerned. We cannot make any real progress here unless either XT catches on, or Core changes fundamentally, but right now XT can't make any progress due to the widespread FUD, censorship and DoS attacks and Core isn't going to change. Stalemate.
