### ISSUE TITLE
0.11.0E : This version is obsolete; upgrade required!

### ISSUE THREAD

**Issue by Conver** [bitcoinxt/bitcoinxt#152]
I believe this is the newest version, but I keep getting "This version is obsolete; upgrade required!" in `getinfo` RPC command, the qt wallet doesn't show the error.

**Comment by dgenr8** [comment]
Bitcoin XT master branch and upcoming "F" release have support for the 
CSV soft fork and BIP9 (including the RPC interface).

The BIP109 (2MB) hard fork also continues to be signaled and supported.

P2Pool might need to be patched to set the 29th bit in the block version 
to signal 2MB support. This was necessary in the past.

Also of interest to miners that have customized CreateNewBlock -- XT has 
not adopted core's major rewrite of that function. That could be helpful 
in applying custom changes.

**Comment by Conver** [comment]
So I can ignore that error?, it is the latest version?

**Comment by dgenr8** [comment]
The warning is caused by version E observing a majority of CSV-support-signaling blocks on the network.

Probably before 2016-07-05, actual CSV transactions will begin to be mined.  Version E will see these transactions as valid in blocks, but will not be able to fully verify that they correctly follow the new rules.  In other words, version E will have only SPV (trust in miners) security for those transactions, and transactions that spend them down the line.  

Therefore you will want to upgrade to version F when available.  Testing the master branch before then would be fantastic if you are able.

**Comment by Conver** [comment]
Just to confirm, that it is now gone with the new version F.

**Comment by Conver** [comment]
Sorry, but its not totally gone.

It is not showing on my bitcoin XT qt on Win64, but its it showing on same version on bitcoind on unix 64.

**Comment by dgenr8** [comment]
Have you checked debug.log? Are there old running processes (`ps xa | grep bitocind`)?  Is your system clock set correctly?

**Comment by dgenr8** [comment]
Obsolete.
