### ISSUE TITLE
Policy on censorship of this site

### ISSUE THREAD

**Issue by UnderTraderGuy** [bitcoinxt/bitcoinxt#34]
Twelve hours ago I opened an issue for adding anonymity to the Bitcoin protocol via XT in a hardfork. Mike Hearn dismissed it, saying the right way was to create a pull request.

I asked if it would be included if I made a pull request.

My request was censored. My github account was deleted. My reddit account was blocked for "making it up" after this website hid all mention of it. Apparently anonymity is so toxic that it can not even be discussed or planned.

Is this the XT way?

**Comment by rromanchuk** [comment]
How was your github account "deleted"?

**Comment by UnderTraderGuy** [comment]
I don't know how, but the username was "UnderTrader" and it gives a "page not found" error.  Issue number 30 also does. Should I just reopen the issue?  It was closed before being deleted. I do not want to misbehave.

**Comment by christophebiocca** [comment]
Contact github support and ask them why you got deleted.

Mike has the power to close issues or to block you from the repo, but I doubt he has direct write access to GitHub's databases.

**Comment by rromanchuk** [comment]
@UnderTraderGuy you need to contact github customer support. Just out of curiosity, did you take any actions that could have gotten you banned from github? 

Don't reopen the issue, submit your pull request directly.

**Comment by mikehearn** [comment]
I didn't do anything to ban or block you in any way. I don't know why github is giving you errors, but it's got nothing to do with me. Additionally issues don't get deleted, only closed. I don't even know if deletion is possible.

It's really hard to say if we'd accept code changes before we actually see them, especially given a very vague one line description. That's why I closed the issue.

I'll close this one too - there's nothing much I can do here.
