### ISSUE TITLE
Tunnel Tor IP download connections through the same proxy as the overall bitcoin connections.

### ISSUE THREAD

**Issue by christophebiocca** [bitcoinxt/bitcoinxt#38]
[From here](http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-August/010379.html)

TL;DR: By downloading Tor IPs in cleartext always we can accidentally leak the real IP of someone operating from behind Tor. Not good.

I may have the time to make a pull request to fix this. Alternatively disabling the lookup if any proxy/tor options are enabled would fix the issue.

**Comment by christophebiocca** [comment]
Wow sorry, turns out [you did anticipate the problem](https://github.com/bitcoinxt/bitcoinxt/pull/20#issuecomment-124496944), and you do [exactly the workaround I was talking about](https://github.com/bitcoinxt/bitcoinxt/commit/73c9efe74c5cc8faea9c2b2c785a2f5b68aa4c23#diff-11780fa178b655146cb414161c635219R265)

That's what I get for taking someone else's bug report at face value.

**Comment by christophebiocca** [comment]
And apparently my undestanding that this is a fix is wrong?

http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-August/010386.html

I lack the in-depth codebase knowledge to evaluate what Peter is saying. It's your call.
Sorry about the issue spam.

**Comment by mikehearn** [comment]
Peter's post is silly. You're about to make a bunch of connections to random computers on the internet that can and sometimes do log your IP along with anything else you send them. Talking to a Tor website as well isn't going to make any noticeable difference to anyone's privacy.

For the avoidance of doubt, our position is this: the IP addresses of Bitcoin nodes are not meant to be secrets *unless* you are running a Tor hidden service. If you are not, then both Core and XT will already try to open up firewalls and NATs using UPnP and generally announce your existence because that's what is best for the health of the network. And it always has done.
