### ISSUE TITLE
Prevent App Nap Check box missing on OSX build

### ISSUE THREAD

**Issue by abelgo** [bitcoinxt/bitcoinxt#44]
I'm having problems with the node going to sleep on OSX 10.10, Basically it stops updating when the mac-book goes into sleep mode and the node becomes unreachable.  In Core there is an option _Prevent App Nap_ Checkbox that comes up on the app _Get Info_   screen, this solved the problem in the past however that check box is not available in the XT osx app.

**Comment by mikehearn** [comment]
It's expected that the app will be suspended when you close the lid, no? Otherwise your laptop would literally never ever shut down and your battery would flatten very quickly.

I'm not sure why the XT and Core packages are different in this respect: both of them have the "disable app nap" setting configured to true in the Info.plist file. So neither should be using App Nap. However, that feature is about suspending an app when it's just sitting in the background, rather than when the laptop itself is sleeping.

**Comment by rromanchuk** [comment]
@abelgo if you're running a node you will need to go into mac os preference pane and adjust your power preferences.  @mikehearn is correct here, App Nap is unrelated to system sleep and is a new "power saving" technique released in Yosemite and higher which attempts to reduce cycles on apps that are not being used by the user. 



> App Nap helps you save power when you’re working with multiple apps at the same time. OS X can tell when an app is completely hidden behind other windows. And if that app isn’t currently doing something for you — playing music, downloading a file, or checking email, for example — App Nap conserves valuable battery life by slowing the app down. But as soon as you start to use it again, the app instantly shifts back to full speed. It’s so seamless you’ll think it had been running that way all along. App Nap works the same way with Safari tabs, so only the visible tab is running at full speed.
