### ISSUE TITLE
Supporting BIP65

### ISSUE THREAD

**Issue by jl2012** [bitcoinxt/bitcoinxt#93]
Adoption of BIP65 has been started and around 1/5 of miners are now mining v4 blocks. XT should merge BIP65 as soon as possible

**Comment by gavinandresen** [comment]
0.11 backport from Core is here:
  https://github.com/bitcoin/bitcoin/pull/6707

... should be easy to merge into XT.

**Comment by jtoomim** [comment]
@gavinandresen @mikehearn I consider this a high priority. If nobody else steps up to merge this (maybe @dgenr8 ? I know he likes pulling stuff from Core), let me know and I can set aside testnet3 stuff to get this done.

**Comment by zander** [comment]
What is the expected result on voting on BIP101 at the same time as voting on BIP65?

Don't they have different, incompatible, voting mechanisms?

**Comment by gavinandresen** [comment]
ACK on supporting BIP65; I'm mostly out until Thursday with meetings, so can't help until then.

Re: voting: will be fine after BIP65 support is merged, assuming all BIP101 miners are also willing to vote for BIP65 (which is a very good assumption).

**Comment by jtoomim** [comment]
@zander : As far as BIP65 is concerned, a vote for BIP65 is a block version > 3. This means that XT is already voting for BIP65. Once 75% of blocks are mined by BIP101 or BIP65 nodes, the BIP65 nodes will enforce BIP65 rules on any node with a version > 3. This means that an invalid OP_CLTV would cause XT blocks to be orphaned by BIP65 nodes, and this could cause a persistent fork if BIP101 hashpower > BIP65 hashpower.

**Comment by jameshilliard** [comment]
> Once 75% of blocks are mined by BIP101 or BIP65 nodes, the BIP65 nodes will enforce BIP65 rules on any node with a version > 3.

This is an interesting side effect of using version numbers for a hardfork attempt without support from most miners, rather than blocks getting orphaned at 95% for non-upgraded clients they get orphaned at 75%. The signaling method for BIP101 should probably be changed, using coinbase sigs for instance would not cause issues like this.

> this could cause a persistent fork if BIP101 hashpower > BIP65 hashpower.

Luckily this is very unlikely to happen on mainnet.

**Comment by jtoomim** [comment]
It's a side effect of having two simultaneous forks with incompatible version schemes. BIP101 used a pre-release draft of version bits (https://github.com/bitcoin/bips/blob/master/bip-0009.mediawiki), whereas BIP65 uses the old and incompatible sequential numbering scheme. Miner support has nothing to do with it. 

Coinbase sigs is an inferior method to version bits as well, since the coinbase sig has other uses like recording prayers into the blockchain or including hashes from a merge-mined share chain in p2pool or some altcoins. Coinbase sigs can't be the place where we put all the metadata that we want to add after the block format was codified because there just isn't enough room. The block version number is where information on feature compatibility belongs. It was created with this role in mind, and that's what it should be used for. There was just disagreement about how it should be used, and the Core team decided (with reasons) to use it in a way that was incompatible with the previously released BIP101.

**Comment by jameshilliard** [comment]
> Miner support has nothing to do with it.

The issue with miner support is that the current method of deploying a fork makes it difficult to indicate support for 2 different changes BIP65 and BIP101 at the same time. Due to BIP101 having nearly no support from miners it isn't really an issue to miners other than those using XT however but this could have been more problematic if there were more.

**Comment by dgenr8** [comment]
See #95

**Comment by jameshilliard** [comment]
So this may be less of an issue at 75% than I originally thought. It may extend an invalid chain once 75% is reached, although it is unlikely an invalid chain will be produced at that point because CLTV is non-standard

**Comment by dgenr8** [comment]
@jameshilliard wrote...
> So this may be less of an issue at 75% than I originally thought. It may extend an invalid chain once 75% is reached, although it is unlikely an invalid chain will be produced at that point because CLTV is non-standard

You were right the first time.  It's an issue since somebody could deliberately mine a BIP101 block with a CTLV script that fails the check.

**Comment by jameshilliard** [comment]
> You were right the first time. It's an issue since somebody could deliberately mine a BIP101 block with a CTLV script that fails the check.

However their block would also get orphaned so this should be less likely to happen. So it is likely this will only be an issue at 95%.

**Comment by chaosgrid** [comment]
>Due to BIP101 having nearly no support from miners it isn't really an issue to miners other than those using XT however but this could have been more problematic if there were more.

There are a lot of assumptions here. Let me also make one: In a few weeks, the network will be saturated and there will be a great push and adoption for XT. There will still be a lot of old XT versions floating around, running on nodes and maybe some miners. This can lead to the situation where at 75% hash power after the January fork deadline, there may be XT nodes and miners that no longer form clear consensus because some of them support BIP65 and some don't. Nodes and miners not supporting BIP65 will probably be a minority but still... if they represent more than 25%, this could lead to a failed hardfork!

Wouldn't it be better to bump the version for BIP(101+65) to have clearly defined behaviour? Or am I missing something here?

**Comment by jameshilliard** [comment]
> Wouldn't it be better to bump the version for BIP(101+65) to have clearly defined behaviour?

This is probably a good idea regardless of weather or not XT gains miner support just so there is a way to differentiate between different types of blocks produced by XT.

**Comment by dgenr8** [comment]
Done in 0.11D.
